[package]
name = "webpki-roots"
version = "0.22.0-riscv"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
readme = "README.md"
license = "MPL-2.0"
description = "Mozilla's CA root certificates for use with webpki"
homepage = "https://github.com/ctz/webpki-roots"
repository = "https://github.com/ctz/webpki-roots"

[dependencies]
rustls-webpki = { git = "https://github.com/jacktemaki/webpki", branch = "untrusted-0.9-riscv" }
